// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0

package database

import (
	"database/sql"
	"time"

	"github.com/google/uuid"
)

type Profile struct {
	ID          uuid.UUID
	UserID      uuid.UUID
	Slug        string
	Username    string
	UpdatedAt   time.Time
	AvatarImage sql.NullString
	CoverImage  sql.NullString
	HeadLine    sql.NullString
}

type Session struct {
	ID           string
	UserID       uuid.UUID
	UserEmail    string
	RefreshToken string
	IsRevoked    bool
	CreatedAt    time.Time
	ExpiresAt    time.Time
}

type User struct {
	ID        uuid.UUID
	CreatedAt time.Time
	UpdatedAt time.Time
	Email     string
	Password  string
}
