-- +goose Up
ALTER TABLE users 
DROP COLUMN api_key,
DROP COLUMN name,
ADD COLUMN email VARCHAR(255) NOT NULL UNIQUE,
ADD COLUMN password VARCHAR(255) NOT NULL;

-- +goose Down
ALTER TABLE users 
ADD COLUMN api_key VARCHAR(64) UNIQUE,
ADD COLUMN name TEXT NOT NULL,
DROP COLUMN email,
DROP COLUMN password;